export const conventions = [
  {
    id: 1,
    title: "Café Loftin",
    logo: "/loftin.jpeg",
    convention: "•	10% de remise sur la restauration ",
    convention1: "•	Pack Gouter : Crêpe/Gaufre + Boisson Chaude = 26 dh",
    convention2:
      "•	Pack Déjeuner : Poutine/Tacos/Sandwich + Soda + Frite : 30 dh",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 2,
    title: "Snack Sa7bi",
    logo: "/sa7bi.jpeg",
    convention: " •	10 % de remise sur toute la carte  ",
    adress: "Rue Chouhada, Oujda 60000",
    map: "",
  },
  {
    id: 3,
    title: "Centre de Beauté ' Iness Beauty ' ",
    logo: "/inessbeauty.jpeg",
    convention: " •	20% de remise ",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 4,
    title: "Librairie Chariqa",
    logo: "/libraire.jpeg",
    convention: "•	10% de remise sur les polycopiés ",
    convention1: "•	50% de remise sur la récupération de données sur PC/USB",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 5,
    title: "Café Mr.Smith",
    logo: "/smith.jpeg",
    convention: " •	30% de remise sur la restauration",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 6,
    title: "Ecole de Musique 'Sami School ' ",
    logo: "/sami.jpeg",
    convention: " •	10% de remise sur l’abonnement mensuel",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 7,
    title: "Milli Gusto",
    logo: "/milli.jpg",
    convention: " •	20% de remise sur le ticket (sauf Soda ou Café)",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 14,
    title: "Café Espace Jasmin",
    logo: "/jasmin.jpeg",
    convention: "• 15% de remise sur les boissons chaudes et la restauration",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 8,
    title: "Parapharmacie  El Meskyny",
    logo: "/parapharmacie.jpg",
    convention: " •	15% de remise sur les produits de la parapharmacie",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 9,
    title: "Opticien Lehlou",
    logo: "/lehlou.jpg",
    convention: " •	Test visuel gratuit ",
    convention1: "• 20% de remise sur (Monture + Verre)",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 10,
    title: "Lunaria",
    logo: "/lunaria.jpeg",
    convention: " •	Soda offert pour tout tacos, burger ou sandwich",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },

  {
    id: 11,
    title: "Gym Corsica",
    logo: "/gym2.jpeg",
    convention: " •	25% de remise pour chaque groupe de 10 personnes",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 11,
    title: "Gym Men Fit",
    logo: "/gym.jpeg",
    convention: "•	25% de remise pour chaque groupe de 10 personnes",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 12,
    title: "Salle de Jeux 'City play'",
    logo: "/cityplay.jpeg",
    convention: " • Entre 10h et 15h : partie jouée = partie offerte",
    convention2:
      " • Petit Snooker : 7 parties = 100dh / 14 parties = 200dh / 22 parties = 300dh",
    convention3:
      " • Grand Snooker : 7 parties pour 150dh / 14 parties = 300dh / 22 parties = 400dh",
    convention4: " • PS4 :7h = 100dh / 14h = 200dh / 21h = 300dh",
    convention5:
      " • 8Ball Pool : 15 parties = 50dh / 33 parties = 100dh / 47 parties = 150dh",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
  {
    id: 13,
    title: "Restaurant Al Affaf",
    logo: "/afaf.jpeg",
    convention:
      " •	Pack 1 : Sandwich (dinde et fromage) + Salade + Boisson à 32DH ",
    convention1: "•	Pack 2 : ¼ Poulet + riz + boisson à 30DH",
    adress: "Rue Miraj، Oujda 60000",
    map: "",
  },
];
