export const galeriedb = [
  {
    id: 4,
    eventName: "Forum ENSAO 2005 ",
    date: "17 & 18 Mars 2005",
    photos: [
      "/forum1.jpg",
      "/forum2.jpg",
      "/forum3.jpg",
      "/forum4.jpg",
      "/forum5.jpg",
      "/forum6.jpg",
      "/forum7.jpg",
      "/forum8.jpg",
      "/forum9.jpg",
    ],
    thumbnail: "/forum.jpeg",
    lieu: "ENSAO / Dar Sebti",
    video: ["https://youtu.be/SWMCpmnNJZo", "https://youtu.be/2G1gFk3jLkI"],
  },
  {
    id: 2,
    eventName: "Rencontre des lauréats ",
    date: "28 Mars 2015",
    photos: [
      "/rencontre1.JPG",
      "/rencontre2.JPG",
      "/rencontre3.JPG",
      "/rencontre4.JPG",
      "/rencontre5.JPG",
      "/rencontre6.JPG",
      "/rencontre7.JPG",
      "/rencontre8.JPG",
      "/rencontre9.JPG",
    ],
    thumbnail: "/rencontre.jpeg",
    lieu: "Hôtel Novotel - Casablanca",
  },

  {
    id: 3,
    eventName: "Ftour Ramadan ",
    date: "04 Juin 2015",
    photos: [
      "/ftour1.jpg",
      "/ftour2.jpg",
      "/ftour3.jpg",
      "/ftour4.jpg",
      "/ftour5.jpg",
      "/ftour6.jpg",
      "/ftour7.jpg",
      "/ftour8.jpg",
      "/ftour9.jpg",
    ],
    thumbnail: "/ftour.jpeg",
    lieu: "Riad 21 - Casablanca",
  },
  {
    id: 6,
    eventName: "EUGO - Eastern University Games of Oujda",
    date: "27/28/29 Fev 2020",
    photos: [
      "/eugo1.jpeg",
      "/eugo2.jpeg",
      "/eugo3.jpeg",
      "/eugo4.jpeg",
      "/eugo5.jpeg",
      "/eugo6.jpeg",
      "/eugo7.jpeg",
      "/eugo8.jpeg",
      "/eugo9.jpeg",
      "/eugo10.jpeg",
      "/eugo11.jpeg",
      "/eugo12.jpeg",
      "/eugo13.jpeg",
      "/eugo14.jpeg",
      "/eugo15.jpeg",
      "/eugo16.jpeg",
    ],
    thumbnail: "cover.jpeg",
    lieu: "Saidia",
    video: ["https://youtu.be/-baS5EG2fVA"],
  },

  {
    id: 5,
    eventName: "Déjeuner ADE & ALENSAO  ",
    date: "09 Janv 2021",
    photos: [
      "/dej1.jpg",
      "/dej2.jpg",
      "/dej3.jpg",
      "/dej4.jpeg",
      "/dej5.jpeg",
      "/dej6.jpeg",
      "/dej7.jpeg",
      "/dej8.jpeg",
      "/dej9.jpeg",
    ],
    thumbnail: "/dej.jpg",
    lieu: "Palmier D'orient - Oujda",
  },
  {
    id: 1,
    eventName: "Assise ADE & ALENSAO ",
    date: "15 Janv 2021",
    photos: [
      "/assise1.jpg",
      "/assise2.jpg",
      "/assise3.jpg",
      "/assise4.jpg",
      "/assise5.jpg",
      "/assise6.JPG",
      "/assise7.JPG",
      "/assise8.JPG",
      "/assise9.JPG",
    ],
    thumbnail: "/assise.jpg",
    lieu: "ENSAO",
  },
  {
    id: 7,
    eventName: " K-LAM 2.0 avec Mme Nawal EL MOUTAWAKEL",
    date: "8 mai 2021",
    photos: [
      "/nawal8.jpeg",
      "/nawal2.jpeg",
      "/nawal3.jpeg",
      "/nawal4.jpeg",
      "/nawal5.jpeg",
      "/nawal6.jpeg",
      "/nawal7.jpeg",
      "/nawal1.jpeg",
    ],
    thumbnail: "/nawalcover1.jpeg",
    lieu: "Bureau de l'AMSD, Stade Mohammed V",
    video: ["https://youtu.be/dkr7xFggZSo"],
  },
  {
    id: 8,
    eventName: "Don du sang",
    date: "26 mai 2021",
    photos: [
      "/sang1.jpeg",
      "/sang2.jpeg",
      "/sang3.jpeg",
      "/sang4.jpeg",
      "/sang5.jpeg",
      "/sang6.jpeg",
      "/sang7.jpeg",
      "/sang8.jpeg",
    ],
    thumbnail: "/coversang.jpg",
    lieu: "ENSAO",
  },
  {
    id: 9,
    eventName: "Inauguration officielle du nouveau bureau de l'ALENSAO",
    date: "22 juin 2021",
    photos: [
      "/alen1.jpeg",
      "/alen4.jpeg",
      "/alen5.jpeg",
      "/alen2.jpeg",
      "/alen3.jpeg",
    ],
    thumbnail: "/alencover.jpeg",
    lieu: "ENSAO",
  },
  {
    id: 10,
    eventName: "Conventions Unicard",
    date: "",
    photos: [
      "/convention1.jpeg",
      "/convention2.jpeg",
      "/convention9.png",
      "/convention10.png",
      "/convention4.jpg",
      "/convention6.png",
      "/convention7.png",
      "/convention8.png",

      "/convention3.jpg",
    ],
    thumbnail: "/convention.png",
    lieu: "ENSAO",
  },
];
